# Generated by Django 4.1.7 on 2023-08-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0002_alter_res_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='res',
            name='status',
            field=models.CharField(default='Not Claimed', max_length=20),
        ),
    ]
