# Generated by Django 4.1.7 on 2023-08-21 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0004_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='SignUp',
        ),
    ]
