# Generated by Django 4.1.7 on 2023-08-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0005_rename_login_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='designation',
            field=models.CharField(choices=[('NGO', 'NGO'), ('Restaurant', 'Restaurant')], default='NGO', max_length=10),
        ),
    ]
