# Generated by Django 4.1.7 on 2023-08-21 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0006_signup_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='designation',
        ),
    ]
