# Generated by Django 4.1.7 on 2023-08-21 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0007_remove_signup_designation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
