# Generated by Django 4.1.7 on 2023-08-21 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0009_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='password',
            new_name='passwo',
        ),
    ]
