# Generated by Django 4.1.7 on 2023-08-21 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0010_rename_password_signup_passwo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='user',
            new_name='username',
        ),
    ]
