# Generated by Django 4.1.7 on 2023-08-21 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0011_rename_user_signup_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='passwo',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='username',
            new_name='user',
        ),
    ]
