# Generated by Django 4.1.7 on 2023-08-21 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0012_rename_passwo_signup_password_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignUp',
            new_name='Sign',
        ),
    ]
